/**
 * Artlab DSL Code Generator
 * Emits JavaScript from an annotated AST.
 *
 * Output shape:
 *   import { ... } from '../runtime/index.js'
 *   export default function buildScene(runtime) { ... }
 */

// ─── CodeGenerator ───────────────────────────────────────────────────────────

export class CodeGenerator {
  /**
   * @param {object} ast - Program AST node (from Parser / SemanticAnalyzer)
   */
  constructor(ast) {
    this.ast = ast;
    this._indent = 0;
    this._lines = [];
    // Track the current object context (name) for light/physics codegen
    this._objectStack = [];
  }

  // ── Public API ────────────────────────────────────────────────────────────

  /**
   * Generates JavaScript source.
   * @returns {{ code: string, sourceMap: string }}
   */
  generate() {
    this._lines = [];
    this._indent = 0;
    this._objectStack = [];

    this._emitHeader();
    this._genProgram(this.ast);
    this._emitFooter();

    const code = this._lines.join('\n');
    // Source map is a placeholder — full source maps would require a mapping table
    const sourceMap = JSON.stringify({ version: 3, sources: [], mappings: '' });
    return { code, sourceMap };
  }

  // ── Emit helpers ─────────────────────────────────────────────────────────

  _pad() {
    return '  '.repeat(this._indent);
  }

  _emit(line) {
    this._lines.push(this._pad() + line);
  }

  _emitRaw(line) {
    this._lines.push(line);
  }

  _emitBlank() {
    this._lines.push('');
  }

  _indented(fn) {
    this._indent++;
    fn();
    this._indent--;
  }

  // ── File header / footer ─────────────────────────────────────────────────

  _emitHeader() {
    this._emit(`// Generated by Artlab DSL Transpiler v0.1.0 — do not edit`);
    this._emit(`import { createScene, createObject, addLight, addPhysics, setCamera, events, anim } from '../runtime/index.js';`);
    this._emitBlank();
  }

  _emitFooter() {
    // nothing extra needed
  }

  // ── Program ──────────────────────────────────────────────────────────────

  _genProgram(node) {
    // Top-level use declarations become comments
    for (const stmt of node.body) {
      if (stmt.type === 'UseDecl') {
        this._genUseDecl(stmt);
      }
    }

    // Top-level function declarations emitted outside buildScene
    for (const stmt of node.body) {
      if (stmt.type === 'FunctionDecl') {
        this._emitBlank();
        this._genFunctionDecl(stmt, true);
      }
    }

    // Top-level let declarations emitted outside buildScene as module-level consts
    for (const stmt of node.body) {
      if (stmt.type === 'LetDecl') {
        this._emitBlank();
        this._genLetDecl(stmt);
      }
    }

    // Scene declarations become the buildScene function
    for (const stmt of node.body) {
      if (stmt.type === 'SceneDecl') {
        this._emitBlank();
        this._genSceneDecl(stmt);
      }
    }
  }

  // ── Use declaration ──────────────────────────────────────────────────────

  _genUseDecl(node) {
    if (node.isUrl) {
      this._emit(`// url-import: ${node.path} (resolved at runtime)`);
    } else {
      this._emit(`// stdlib: ${node.path} (resolved at runtime)`);
    }
  }

  // ── Scene declaration ────────────────────────────────────────────────────

  _genSceneDecl(node) {
    this._emit(`export default function buildScene(runtime) {`);
    this._indented(() => {
      for (const item of node.body) {
        this._genSceneItem(item);
      }
    });
    this._emit(`}`);
  }

  _genSceneItem(node) {
    switch (node.type) {
      case 'CameraBlock':   return this._genCameraBlock(node);
      case 'ObjectDecl':    return this._genObjectDecl(node);
      case 'LetDecl':       return this._genLetDecl(node);
      case 'EventHandler':  return this._genEventHandler(node);
      case 'FunctionDecl':  return this._genFunctionDecl(node, false);
      default:
        this._emit(`/* unhandled scene item: ${node.type} */`);
    }
  }

  // ── Camera ───────────────────────────────────────────────────────────────

  _genCameraBlock(node) {
    const propsObj = this._genPropsObject(node.props);
    this._emit(`runtime.camera.set({ type: ${JSON.stringify(node.cameraType)}, ${propsObj} });`);
  }

  // ── Object declaration ───────────────────────────────────────────────────

  _genObjectDecl(node) {
    this._emitBlank();
    this._objectStack.push(node.name);

    // Separate the items into geometry/material and sub-blocks
    const geomProps = [];
    const materialBlocks = [];
    const lightBlocks = [];
    const physicsBlocks = [];
    const otherProps = [];

    for (const item of node.items) {
      if (item.type === 'MaterialBlock') materialBlocks.push(item);
      else if (item.type === 'LightBlock') lightBlocks.push(item);
      else if (item.type === 'PhysicsBlock') physicsBlocks.push(item);
      else if (item.type === 'PropAssign') otherProps.push(item);
    }

    // Build the object options
    const parts = [];
    for (const prop of otherProps) {
      parts.push(`${JSON.stringify(prop.key)}: ${this._genExpr(prop.value)}`);
    }
    for (const mat of materialBlocks) {
      parts.push(`material: { type: ${JSON.stringify(mat.materialType)}, ${this._genPropsObject(mat.props)} }`);
    }

    const partsStr = parts.length > 0 ? ', ' + parts.join(', ') : '';
    this._emit(`runtime.scene.add(${JSON.stringify(node.name)}, {${partsStr} });`);

    // Lights
    for (const light of lightBlocks) {
      const propsObj = this._genPropsObject(light.props);
      this._emit(`runtime.scene.addLight({ type: ${JSON.stringify(light.lightType)}, objectName: ${JSON.stringify(node.name)}, ${propsObj} });`);
    }

    // Physics
    for (const phys of physicsBlocks) {
      const propsObj = this._genPropsObject(phys.props);
      this._emit(`runtime.physics.addBody(${JSON.stringify(node.name)}, { type: ${JSON.stringify(phys.physicsType)}, ${propsObj} });`);
    }

    this._objectStack.pop();
  }

  // ── Event handler ────────────────────────────────────────────────────────

  _genEventHandler(node) {
    this._emitBlank();
    const eventKey = `${node.namespace}:${node.event}`;

    // Build destructured arg list
    let argDestructure = '';
    if (node.args.length > 0) {
      const argNames = node.args.map(a => {
        if (a.type === 'Identifier') return a.name;
        return this._genExpr(a);
      });
      argDestructure = `{ ${argNames.join(', ')} }`;
    } else {
      argDestructure = '_evt';
    }

    this._emit(`runtime.events.on(${JSON.stringify(eventKey)}, (${argDestructure}) => {`);
    this._indented(() => {
      for (const stmt of node.body) {
        this._genBodyStmt(stmt);
      }
    });
    this._emit(`});`);
  }

  // ── Function declaration ─────────────────────────────────────────────────

  _genFunctionDecl(node, toplevel) {
    const params = node.params.join(', ');
    this._emit(`function ${node.name}(${params}) {`);
    this._indented(() => {
      for (const stmt of node.body) {
        this._genBodyStmt(stmt);
      }
    });
    this._emit(`}`);
  }

  // ── Body statements ──────────────────────────────────────────────────────

  _genBodyStmt(node) {
    switch (node.type) {
      case 'LetDecl':      return this._genLetDecl(node);
      case 'ReturnStmt':   return this._genReturnStmt(node);
      case 'IfStmt':       return this._genIfStmt(node);
      case 'RepeatStmt':   return this._genRepeatStmt(node);
      case 'AnimateStmt':  return this._genAnimateStmt(node);
      case 'ToggleStmt':   return this._genToggleStmt(node);
      case 'ExprStmt':     return this._genExprStmt(node);
      case 'FunctionDecl': return this._genFunctionDecl(node, false);
      default:
        this._emit(`/* unhandled stmt: ${node.type} */`);
    }
  }

  // ── Let declaration ──────────────────────────────────────────────────────

  _genLetDecl(node) {
    this._emit(`let ${node.name} = ${this._genExpr(node.init)};`);
  }

  // ── Return statement ─────────────────────────────────────────────────────

  _genReturnStmt(node) {
    if (node.value) {
      this._emit(`return ${this._genExpr(node.value)};`);
    } else {
      this._emit(`return;`);
    }
  }

  // ── If statement ─────────────────────────────────────────────────────────

  _genIfStmt(node) {
    this._emit(`if (${this._genExpr(node.test)}) {`);
    this._indented(() => {
      for (const s of node.consequent) this._genBodyStmt(s);
    });
    if (node.alternate && node.alternate.length > 0) {
      this._emit(`} else {`);
      this._indented(() => {
        for (const s of node.alternate) this._genBodyStmt(s);
      });
    }
    this._emit(`}`);
  }

  // ── Repeat statement ─────────────────────────────────────────────────────

  _genRepeatStmt(node) {
    const count = this._genExpr(node.count);
    this._emit(`for (let _i = 0; _i < ${count}; _i++) {`);
    this._indented(() => {
      for (const s of node.body) this._genBodyStmt(s);
    });
    this._emit(`}`);
  }

  // ── Animate statement ────────────────────────────────────────────────────

  _genAnimateStmt(node) {
    const target = this._genExpr(node.target);
    const from   = this._genExpr(node.from);
    const to     = this._genExpr(node.to);
    const over   = this._genDurationExpr(node.over);
    const ease   = node.ease ? `, ease: ${JSON.stringify(node.ease)}` : '';
    this._emit(`runtime.anim.tween({ target: ${JSON.stringify(target)}, from: ${from}, to: ${to}, duration: ${over}${ease} });`);
  }

  // ── Toggle statement ─────────────────────────────────────────────────────

  _genToggleStmt(node) {
    const target = this._genExpr(node.target);
    this._emit(`runtime.scene.toggle(${JSON.stringify(target)});`);
  }

  // ── Expression statement ─────────────────────────────────────────────────

  _genExprStmt(node) {
    this._emit(`${this._genExpr(node.expr)};`);
  }

  // ── Expression generators ────────────────────────────────────────────────

  _genExpr(node) {
    if (!node) return 'undefined';
    switch (node.type) {
      case 'NumberLiteral': return this._genNumberLiteral(node);
      case 'StringLiteral': return JSON.stringify(node.value);
      case 'ColorLiteral':  return `0x${node.value}`;
      case 'BoolLiteral':   return String(node.value);
      case 'Identifier':    return node.name;
      case 'BinaryExpr':    return this._genBinaryExpr(node);
      case 'UnaryExpr':     return this._genUnaryExpr(node);
      case 'CallExpr':      return this._genCallExpr(node);
      case 'MemberExpr':    return this._genMemberExpr(node);
      case 'VecLiteral':    return this._genVecLiteral(node);
      default:
        return `/* unknown expr: ${node.type} */`;
    }
  }

  _genNumberLiteral(node) {
    if (node.unit) {
      // Units are passed as structured objects for runtime interpretation
      return `{ value: ${node.value}, unit: ${JSON.stringify(node.unit)} }`;
    }
    return String(node.value);
  }

  _genBinaryExpr(node) {
    const left  = this._genExpr(node.left);
    const right = this._genExpr(node.right);
    return `(${left} ${node.op} ${right})`;
  }

  _genUnaryExpr(node) {
    return `${node.op}${this._genExpr(node.operand)}`;
  }

  _genCallExpr(node) {
    const args = node.args.map(a => this._genExpr(a)).join(', ');
    if (typeof node.callee === 'string') {
      return `${node.callee}(${args})`;
    }
    return `${this._genExpr(node.callee)}(${args})`;
  }

  _genMemberExpr(node) {
    return `${this._genExpr(node.object)}.${node.property}`;
  }

  _genVecLiteral(node) {
    const comps = node.components.map(c => this._genExpr(c)).join(', ');
    if (node.components.length === 2) {
      return `new THREE.Vector2(${comps})`;
    }
    return `new THREE.Vector3(${comps})`;
  }

  // ── Duration expression: over 0.1s → duration in ms ─────────────────────

  _genDurationExpr(node) {
    if (node.type === 'NumberLiteral') {
      if (node.unit === 's') {
        return String(node.value * 1000);
      }
      if (node.unit === 'ms') {
        return String(node.value);
      }
      // No unit — assume seconds
      return String(node.value * 1000);
    }
    // Non-trivial expression — emit as-is and let runtime handle it
    return this._genExpr(node);
  }

  // ── Props object helper ──────────────────────────────────────────────────

  _genPropsObject(props) {
    if (!props || props.length === 0) return '';
    return props
      .map(p => `${JSON.stringify(p.key)}: ${this._genExpr(p.value)}`)
      .join(', ');
  }
}
